In [ ]:
!pip install openpyxl

Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)

In [ ]:
import pandas as pd

In [7]:
import os

print(os.listdir("/content/sample_data"))

['README.md', 'anscombe.json', 'inventory_data.xlsx', 'hospital_bed_resource_management .csv.xlsx', 'california_housing_test.csv', 'mnist_train_small.csv', 'mnist_test.csv', 'california_housing_train.csv']

In [8]:
import pandas as pd

dataset1 = pd.read_excel("/content/sample_data/inventory_data.xlsx")

dataset2 = pd.read_excel("/content/sample_data/hospital_bed_resource_management .csv.xlsx")

In [9]:
dataset1.head()

,Date,Item_ID,Item_Type,Item_Name,Current_Stock,Min_Required,Max_Capacity,Unit_Cost,Avg_Usage_Per_Day,Restock_Lead_Time,Vendor_ID
0,2024-10-01,105,Consumable,Ventilator,1542,264,1018,4467.55,108,17,V001
1,2024-10-02,100,Equipment,Ventilator,2487,656,3556,5832.29,55,12,V001
2,2024-10-03,103,Equipment,Surgical Mask,2371,384,5562,16062.98,470,6,V001
3,2024-10-04,103,Consumable,Surgical Mask,2038,438,1131,744.10,207,15,V002
4,2024-10-05,107,Equipment,IV Drip,2410,338,1013,15426.53,158,12,V003

In [10]:
dataset2.head()

,Patient_ID,Admission_Date,Discharge_Date,Primary_Diagnosis,Procedure_Performed,Room_Type,Bed_Days,Supplies_Used,Equipment_Used,Staff_Needed,Length of stay _days
0,P001,2025-03-13 00:00:00,2025-03-17 00:00:00,Diabetes,Appendectomy,General Ward,2,"Gloves, IV",Surgical Table,2 Surgeons,4
1,P002,2025-03-14 00:00:00,2025-03-18 00:00:00,Fracture,Appendectomy,ICU,10,"Gown, IV",MRI Machine,1 Nurse,8
2,P003,2025-03-15 00:00:00,2025-03-19 00:00:00,Fracture,Chest X-ray,ICU,10,"Gloves, IV",X-ray Machine,"1 Nurse, 1 Doctor",18
3,P004,2025-03-16 00:00:00,2025-03-20 00:00:00,Diabetes,Chest X-ray,ICU,11,"Gloves, IV",X-ray Machine,1 Nurse,5
4,P005,2025-03-17 00:00:00,2025-03-21 00:00:00,Appendicitis,MRI,ICU,2,"Gloves, IV",X-ray Machine,2 Surgeons,9

In [11]:
dataset1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Date               500 non-null    datetime64[ns]
 1   Item_ID            500 non-null    int64
 2   Item_Type          500 non-null    object
 3   Item_Name          500 non-null    object
 4   Current_Stock      500 non-null    int64
 5   Min_Required       500 non-null    int64
 6   Max_Capacity       500 non-null    int64
 7   Unit_Cost          500 non-null    float64
 8   Avg_Usage_Per_Day  500 non-null    int64
 9   Restock_Lead_Time  500 non-null    int64
 10  Vendor_ID          500 non-null    object
dtypes: datetime64[ns](1), float64(1), int64(6), object(3)
memory usage: 43.1+ KB

In [12]:
dataset2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 11 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Patient_ID            500 non-null    object
 1   Admission_Date        500 non-null    object
 2   Discharge_Date        500 non-null    object
 3   Primary_Diagnosis     500 non-null    object
 4   Procedure_Performed   500 non-null    object
 5   Room_Type             500 non-null    object
 6   Bed_Days              500 non-null    int64
 7   Supplies_Used         500 non-null    object
 8   Equipment_Used        500 non-null    object
 9   Staff_Needed          500 non-null    object
 10  Length of stay _days  500 non-null    int64
dtypes: int64(2), object(9)
memory usage: 43.1+ KB

In [13]:
dataset1.describe()

,Date,Item_ID,Current_Stock,Min_Required,Max_Capacity,Unit_Cost,Avg_Usage_Per_Day,Restock_Lead_Time
count,500,500.000000,500.000000,500.000000,500.000000,500.00000,500.000000,500.000000
mean,2025-06-07 12:00:00,104.508000,2458.644000,485.982000,3288.834000,10277.32598,261.804000,15.116000
min,2024-10-01 00:00:00,100.000000,69.000000,10.000000,500.000000,4.23000,2.000000,1.000000
25%,2025-02-02 18:00:00,102.000000,1307.750000,215.750000,1847.750000,5422.46250,150.500000,7.000000
50%,2025-06-07 12:00:00,104.000000,2411.500000,496.500000,3311.000000,10129.96000,257.000000,16.000000
75%,2025-10-10 06:00:00,107.000000,3719.000000,734.250000,4696.000000,15206.31500,392.000000,23.000000
max,2026-02-12 00:00:00,109.000000,4976.000000,995.000000,5992.000000,19984.16000,499.000000,29.000000
std,NaN,2.865372,1390.078133,292.054772,1602.646278,5728.68441,143.983318,8.610856

In [14]:
dataset2.describe()

         Bed_Days  Length of stay _days
count  500.000000            500.000000
mean     7.364000             10.188000
std      4.079803              5.935581
min      1.000000              1.000000
25%      4.000000              5.000000
50%      7.000000             10.000000
75%     11.000000             15.000000
max     14.000000             20.000000

In [15]:
dataset1.isnull().sum()

Date                 0
Item_ID              0
Item_Type            0
Item_Name            0
Current_Stock        0
Min_Required         0
Max_Capacity         0
Unit_Cost            0
Avg_Usage_Per_Day    0
Restock_Lead_Time    0
Vendor_ID            0
dtype: int64

In [16]:
dataset2.isnull().sum()

Patient_ID              0
Admission_Date          0
Discharge_Date          0
Primary_Diagnosis       0
Procedure_Performed     0
Room_Type               0
Bed_Days                0
Supplies_Used           0
Equipment_Used          0
Staff_Needed            0
Length of stay _days    0
dtype: int64

In [17]:
dataset1.columns

Index(['Date', 'Item_ID', 'Item_Type', 'Item_Name', 'Current_Stock',
       'Min_Required', 'Max_Capacity', 'Unit_Cost', 'Avg_Usage_Per_Day',
       'Restock_Lead_Time', 'Vendor_ID'],
      dtype='object')

In [18]:
dataset2.columns

Index(['Patient_ID', 'Admission_Date', 'Discharge_Date', 'Primary_Diagnosis',
       'Procedure_Performed', 'Room_Type', 'Bed_Days', 'Supplies_Used',
       'Equipment_Used', 'Staff_Needed', 'Length of stay _days'],
      dtype='object')